### ISSUE TITLE
approval/rejection email subject lines to be more "friendly"

### ISSUE THREAD

**Issue by joncle** [python-jobs-board/pythondotorg#12]
As per discussion in #11 - subject lines should be prefixed with `Python Job Board:` and depending on the event:
- The position for {{ job_title}} has now been listed.
- The position for {{ job_title }} has not been accepted - please see details.

Or similar...

**Comment by smontanaro** [comment]
Seems like it's going to generate some rather long subject lines...

**Comment by joncle** [comment]
@smontanaro Potentially, but better than short and blunt imho - do you have any suggestions for something "in between"? I've cc'd the jobs list to advise that subject lines and body for emails are up for commenting on... If you have any particular suggestion/stance on this - please let us know.

There's more to be cracking on with, but it'd be nice if we could get input/thoughts in the mean time...

**Comment by smontanaro** [comment]
Been awhile since I handled any of these submissions manually.  It might be
worth asking on jobs@python.org for feedback from the folks who have more
recently processed postings through the old system.

I don't think there's anything wrong with a totally canned subject like
"Job submission response," and push all the details (job title,
accept/reject status, etc) into the message body.

Skip

**Comment by joncle** [comment]
@smontanaro they're already informed as of about 20 minutes ago - we'll see what they suggest...  I personally prefer something that may looked canned but is more specific to the listing submitted, but I'm not worrying either way - we'll go with what we've got and see what the reviewers suggest from the list.

**Comment by malemburg** [comment]
I'd suggest to use these subject lines:
- "Python Job Board: Job entry approved"
- "Python Job Board: Job entry could not be accepted"

**Comment by wbachnik** [comment]
I just updated the email subject templates in 298f8e05a9f13c2bbfd14fe34005cf2088d55c68

**Comment by malemburg** [comment]
Great. Thanks, Wiktor.
