### ISSUE TITLE
Internal Server Error when leaving the company field empty

### ISSUE THREAD

**Issue by malemburg** [python-jobs-board/pythondotorg#15]
You can see the problem when visiting job entry:

https://www.python.org/newjobs/142/review/

on the main site. Here's the jobs record:

https://www.python.org/admin/jobs/job/142/

This has the company name set, but the company field empty.

Important: It is not 100% clear whether the new site is already using the current version of the jobs board, since it usually takes up to an hour for the update to get applied.

**Comment by joncle** [comment]
Umm. I would expect some missing data maybe - not necessarily a server error.

I have noticed that:

`<p><strong>Company:</strong> {{ object.company.name }}</p>` from https://github.com/python-jobs-board/pythondotorg/blob/master/templates/jobs/job_review.html#L29 should be: `<p><strong>Company:</strong> {{ object.company_name }}</p>` - note (the `_` instead of the `.`)

**Comment by joncle** [comment]
Okay. updated `job_review.html` to use `display_name` and `display_description` instead of what was there... needed changing anyway, but surprised if it's the cause of the internal error.

**Comment by malemburg** [comment]
@joncle: The server error does not happen on the review listing screen. It happens when opening the job posting details page.

**Comment by malemburg** [comment]
https://github.com/python-jobs-board/pythondotorg/blob/master/templates/jobs/job_detail.html#L29 apparently has the same problem as the one you fixed on the review listing page.

**Comment by malemburg** [comment]
Looking through the templates, there are still quite a few instances of object.company.name in use. These will all fail if the company field is NULL/None.

**Comment by joncle** [comment]
@malemburg https://github.com/python-jobs-board/pythondotorg/commit/b1684aa5fb366228bcf89181debe04e6ff9264d4 should fix this...

**Comment by malemburg** [comment]
Fixed now.
