### ISSUE TITLE
Job type field is not set in the edit form for existing jobs

### ISSUE THREAD

**Issue by malemburg** [python-jobs-board/pythondotorg#17]
See e.g. https://www.python.org/newjobs/145/edit/

When entering the job, I had ticked the "Django" type, but this was not stored in the database. Trying to add it later also doesn't store the checked types.

**Comment by frankwiles** [comment]
Yep, views weren't properly handling the m2m relationship there. Fixed upstream.

**Comment by malemburg** [comment]
Confirmed working on staging.python.org
