### ISSUE TITLE
Job title cannot be entered in the jobs entry form

### ISSUE THREAD

**Issue by malemburg** [python-jobs-board/pythondotorg#18]
See e.g. https://www.python.org/newjobs/145/edit/ and then https://www.python.org/newjobs/145/

There's no entry field for the jobs title. It is always set to None.

**Comment by malemburg** [comment]
This is particularly bad, since the jobs listing will use the job title as link to the full job entry. Without title, no link is displayed and it's impossible to even see the details.

**Comment by frankwiles** [comment]
Fixed upstream.

**Comment by malemburg** [comment]
Confirmed working on staging.python.org
