### ISSUE TITLE
Comment previews have no CSS styling

### ISSUE THREAD

**Issue by malemburg** [python-jobs-board/pythondotorg#19]
When clicking on "preview" under the job comments area, a page comes up with no CSS styling.

This is the HTML head part of the page:

```
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Preview your comment</title>
</head>
<body>
```

**Comment by SarahPythonista** [comment]
Will be fixed by [issue #591 in upstream](https://github.com/python/pythondotorg/issues/591).
