### ISSUE TITLE
Generate a rejection email whenever a job entry is changed to "rejected"

### ISSUE THREAD

**Issue by malemburg** [python-jobs-board/pythondotorg#2]
Here's an email template:
""""
Dear {{name}},

Thank you for choosing to list your vacancy on python.org's Job Board.

Unfortunately, your listing does not comply to our Job Board listing
guidelines (see https://www.python.org/community/jobs/howto/). If possible,
please update your listing and resubmit the request.

Many thanks,
{{ review_name }}
Python Job Board
""""

**Comment by wbachnik** [comment]
Please review the PR #11 it implements sending the rejection notification email.

**Comment by malemburg** [comment]
Can this ticket be closed ?

**Comment by wbachnik** [comment]
I don't see any more code changes required, so IMO yes, if you/reviewers are happy with the result.
