### ISSUE TITLE
Posting a job comment returns a moderation page

### ISSUE THREAD

**Issue by malemburg** [python-jobs-board/pythondotorg#20]
The page shown when posting a comment on the job says:

"""
Thank you for your comment

A moderator will review the post before it becomes available on the site.
"""

This doesn't make sense, since there is no moderator for these comments.

The system should return to the job page and show the comment.

**Comment by frankwiles** [comment]
Actually we're using the comment moderation features built into Django to allow the submitter and site admins to communicate about the job.  I'll make the explanation text more clear, but those comments are only visible to the creator and the moderators.

**Comment by SarahPythonista** [comment]
Will be fixed by [issue #591 in upstream](https://github.com/python/pythondotorg/issues/591).
