### ISSUE TITLE
Job comment emails are missing a few details

### ISSUE THREAD

**Issue by malemburg** [python-jobs-board/pythondotorg#21]
I posted a comment on a job and received this email as result:

```
Marc-Andre Lemburg,

There is a new comment on your job posting.

Post: 
URL:  http://python.org/newjobs/145/
Sent by: None, 06/04/2014

--- Comment: ---
This is a test comment on job 145.

--
Kind regards,
python.org
```

Note that I had entered "Marc" as name.

The comment shows up on the job as by "Marc-Andre Lemburg" - which is my user name, not the one I had entered in the comments field:

https://www.python.org/newjobs/145/

**Comment by SarahPythonista** [comment]
Will be fixed by [issue #591 in upstream](https://github.com/python/pythondotorg/issues/591).
