### ISSUE TITLE
Job review listing could use some CSS tweaks

### ISSUE THREAD

**Issue by malemburg** [python-jobs-board/pythondotorg#22]
Looking at https://www.python.org/newjobs/review/ the listing could use some care to e.g. 
- add more spacing between the columns
- add an edit button which goes to the edit page (instead of having to click on the id number)
- show the job category
- show titles is title case instead of all lower case
- allow sorting by clicking on the titles (this may be better done in a separate ticket)

**Comment by SarahPythonista** [comment]
Please track this in [#447 in upstream](https://github.com/python/pythondotorg/issues/447).
