### ISSUE TITLE
Job links give a 404 in the jobs listing

### ISSUE THREAD

**Issue by malemburg** [python-jobs-board/pythondotorg#28]
Clicking on one of the job title links in the job listing https://www.python.org/newjobs/ always gives a 404. It seems the links are pointing to the wrong page, e.g. https://www.python.org/newjobs/99/

**Comment by malemburg** [comment]
What's strange is that some links do work, e.g. https://www.python.org/newjobs/146/

**Comment by frankwiles** [comment]
Was do to an errant restriction on the detail page adhering to a 90 day threshold that is used in other parts of the Jobs app to keep things like "current" jobs down to a reasonable number.  Fixed upstream.

**Comment by malemburg** [comment]
Confirmed working on staging.python.org
