### ISSUE TITLE
Remove company name popup

### ISSUE THREAD

**Issue by sdeibel** [python-jobs-board/pythondotorg#35]
It's confusing to have a company popup and a free-form field, and adds implementation complexity.  I'd recommend removing that and just having people type in the company name.  If not removed, would need a way to add to the popup from the manually entered field.

**Comment by sdeibel** [comment]
There's also a confusing behavior if you select from the popup and enter a company description.  It says you can't do that.  Which maybe is fine, but then grey out the name/description when a company is chosen from the popup.

**Comment by frankwiles** [comment]
That's a good point.  Filed it upstream here https://github.com/python/pythondotorg/issues/565

**Comment by sdeibel** [comment]
Thanks.  I still think it would be better to just remove the popup.  I don't see why the website needs to manage a list of companies.  Seems like unnecessary structure to me.  Also, this field could just be pre-filled with the name of the company for the logged-in user so they only have to type it once.

**Comment by frankwiles** [comment]
I wasn't involved in the design of this, but I believe the original idea was to have some of the more prolific Python companies have better structured data in the apps.  This way we can for example list open jobs at Industrial Light & Magic along with their success stories, view all of their open/past jobs, perhaps some day list PSF members who work there, etc.

**Comment by malemburg** [comment]
On 11.02.2015 19:26, Frank Wiles wrote:

> I wasn't involved in the design of this, but I believe the original idea was to have some of the more prolific Python companies have better structured data in the apps.  This way we can for example list open jobs at Industrial Light & Magic along with their success stories, view all of their open/past jobs, perhaps some day list PSF members who work there, etc. 

In practice this won't work out, though, since companies tend to
want to put job specific descriptions in their company listings.

It's also likely that we'll get postings from different departments
within companies, different company sites, etc. who will want to
use different descriptions.

Let's drop the feature for now until we find some use for it
at some later stage.

## Thanks,

Marc-Andre Lemburg
Director
Python Software Foundation
http://www.python.org/psf/

**Comment by frankwiles** [comment]
Fixed upstream with https://github.com/python/pythondotorg/commit/98db0ed58e9b52f4ea1f1d94ef3eb4261ce439d6
