### ISSUE TITLE
Missing Technologies / Add "Other" box

### ISSUE THREAD

**Issue by sdeibel** [python-jobs-board/pythondotorg#39]
On the form in Technologies, missing Turbogears, PySide (could just list PyQt/PySide), Google App Engine, wxPython, and probably a gazillion other things (Blender, Maya, NUKE, etc) so maybe it should have an "Other:" box?

**Comment by frankwiles** [comment]
These options are editable in the admin at /admin/jobs/jobtype/ ('Job Technologies' model link) and I believe the 'Requirements' section was intended to be used for 'Other' stuff.  But definitely open to having an 'other' box for the technologies if the PSF wants it.

**Comment by malemburg** [comment]
On 11.02.2015 19:06, Frank Wiles wrote:

> These options are editable in the admin at /admin/jobs/jobtype/ ('Job Technologies' model link) and I believe the 'Requirements' section was intended to be used for 'Other' stuff.  But definitely open to having an 'other' box for the technologies if the PSF wants it. 

Yes, please.

## 

Marc-Andre Lemburg
Director
Python Software Foundation
http://www.python.org/psf/

**Comment by frankwiles** [comment]
Moved Issue upstream to here https://github.com/python/pythondotorg/issues/575
Fixed here https://github.com/python/pythondotorg/commit/7e848ca63f332036ef94b00e2df533c8aa07ed1c
