### ISSUE TITLE
Add "canned" comments which can be selected via a drop-down on the job details page

### ISSUE THREAD

**Issue by malemburg** [python-jobs-board/pythondotorg#4]
Canned comment response texts:
- (Voluntary work): "The Python Job Board is for paid positions only. The Python Community has a separate Wiki for listing voluntary positions available at http://wiki.python.org/moin/VolunteerOpportunities."
  - (Not Python - for obviously non-Python roles - if ambiguous then that's clarified by querying submission): "The Python Job Board is for positions in which the primary role involves the Python programming language or development frameworks based on Python."

These can then be used as basis for rejection comments explaining the the reason for rejection. Once selected, the comments field should be filled with the text to allow more details edits as necessary.

**Comment by joncle** [comment]
The easiest way I imagine this is to be a `select` field in the template with a bit of javascript to auto populate a textarea. Ideally we should have editable canned reasons in the database, but for short term I think it's overkill and by itself should be part of some other migration if needed.

**Comment by malemburg** [comment]
On 02.05.2014 21:16, Jon Clements wrote:

> The easiest way I imagine this is to be a `select` field in the template with a bit of javascript to auto populate a textarea. Ideally we should have editable canned reasons in the database, but for short term I think it's overkill and by itself should be part of some other migration if needed.

Fully agreed :-)

## 

Marc-Andre Lemburg

**Comment by wbachnik** [comment]
Please see PR #13. It contains a basic implementation of this idea. Comment text is hardcoded as JS strings in the template.

**Comment by malemburg** [comment]
On 12.05.2014 23:19, Wiktor Bachnik wrote:

> Please see PR #13. It contains a basic implementation of this idea. Comment text is hardcoded as JS strings in the template.

Looks good.

## 

Marc-Andre Lemburg
