### ISSUE TITLE
Wrong "log in here" link

### ISSUE THREAD

**Issue by sdeibel** [python-jobs-board/pythondotorg#40]
The link "log in here" on the right under Submit a Job links to the new job page and not the login screen.

**Comment by frankwiles** [comment]
Can't reproduce this, sidebar link goes to: https://staging.python.org/accounts/login/?next=/newjobs/create/

**Comment by sdeibel** [comment]
Yes, but it's confusing because that's the new jobs form and not a login page as the link text leads me to expect.  Maybe the issue is only there if already logged in?  Presumably it just shouldn't have this link in this case.  Somewhat related is the fact that it says "update job existing postings" (which probably should omit the word "job") and that doesn't link to anywhere and I can't really find my job postings.

**Comment by frankwiles** [comment]
Ah ok now I'm following you, will get it fixed. I thought you were saying the login link didn't lead to the login form, but yes it is confusing for people logged in.

**Comment by sdeibel** [comment]
Great, thanks.  And yes, I was logged in and trying to find a list of my past jobs (which might be empty b/c I submitted some test ones but maybe they were never approved)

**Comment by frankwiles** [comment]
Fixed upstream https://github.com/python/pythondotorg/issues/564 will be live on staging soon
