### ISSUE TITLE
Invalid Stay Up To Date links

### ISSUE THREAD

**Issue by sdeibel** [python-jobs-board/pythondotorg#41]
The Subscribe via RSS and Follow via Twitter links on the right do not go anywhere.  It's also unclear if either of these features have been implemented.

**Comment by frankwiles** [comment]
Filed upstream https://github.com/python/pythondotorg/issues/568

**Comment by frankwiles** [comment]
Fixed upstream with https://github.com/python/pythondotorg/commit/c0ee3aa5276a5d825c748b77aea0ae50c512c297
