### ISSUE TITLE
Pointer to Andrew Dalke's version of Python 0.9.1p1 release

### ISSUE THREAD

**Issue by smontanaro** [python-jobs-board/pythondotorg#43]
Received this at webmaster@python.org... I could have sworn we already had a reference somewhere on the site. Since the reference is to the legacy site (which the download/releases stuff still references), I don't know what's necessary to actually create a patch for the new site.

---

Jan van Haarst jan@vanhaarst.net
to webmaster 

Hi ,

in http://legacy.python.org/download/releases/src/README it says :
# Older sources

If you find an older Python release (e.g. 0.9.8), we're interested
in getting a copy!  webmaster@python.org

​I just found this :​

http://www.dalkescientific.com/writings/diary/archive/2009/03/27/python_0_9_1p1.html

​So, you could add that to the list !

**Comment by malemburg** [comment]
On 15.02.2015 14:07, Skip Montanaro wrote:

> Received this at webmaster@python.org... I could have sworn we already had a reference somewhere on the site. Since the reference is to the legacy site (which the download/releases stuff still references), I don't know what's necessary to actually create a patch for the new site.

Hi Skip,

you posted this on the jobs board tracker. I think you wanted the
upstream tracker at https://github.com/python/pythondotorg/issues

> ---
> 
> Jan van Haarst jan@vanhaarst.net
> to webmaster 
> 
> Hi ,
> 
> in http://legacy.python.org/download/releases/src/README it says :
> 
> # Older sources
> 
> If you find an older Python release (e.g. 0.9.8), we're interested
> in getting a copy!  webmaster@python.org
> 
> ​I just found this :​
> 
> http://www.dalkescientific.com/writings/diary/archive/2009/03/27/python_0_9_1p1.html
> 
> ​So, you could add that to the list !
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/python-jobs-board/pythondotorg/issues/43

## 

Marc-Andre Lemburg
Director
Python Software Foundation
http://www.python.org/psf/

**Comment by smontanaro** [comment]
On Sun, Feb 15, 2015 at 7:17 AM, Marc-Andre Lemburg <
notifications@github.com> wrote:

> you posted this on the jobs board tracker. I think you wanted the
> upstream tracker at https://github.com/python/pythondotorg/issues

Thanks.

We have too many friggin' trackers.

S
