### ISSUE TITLE
Field validation errors on /newjobs/create need to be fixed

### ISSUE THREAD

**Issue by joncle** [python-jobs-board/pythondotorg#6]
Once #5 is completed the CSS for form validation errors upon submitting a new job needs to be corrected, eg:

![screenshot from 2014-05-02 19 57 44](https://cloud.githubusercontent.com/assets/2022241/2866719/f3de5e3c-d22b-11e3-9958-f71528d67791.png)

and...

![screenshot from 2014-05-02 19 56 56](https://cloud.githubusercontent.com/assets/2022241/2866721/f82eceae-d22b-11e3-82a9-0d4596e04fcd.png)

**Comment by wbachnik** [comment]
I provided a very simplistic fix for that problem, please check the [PR](https://github.com/python-jobs-board/pythondotorg/pull/9).
I think the form could be styled a bit better and I can try doing that once more important tasks are complete.

**Comment by wbachnik** [comment]
This is fixed by PR #9 and PR #10 and ready for verification.

**Comment by wbachnik** [comment]
Since both my PRs are merged and my testing shows that the problem went away, I'm marking this as fixed. Reopen if needed.
